"use strict";
var Strings_1 = require("./Strings");
exports.printf = Strings_1.printf;
exports.createFormatter = Strings_1.createFormatter;
exports.format = Strings_1.format;
exports.repeat = Strings_1.repeat;
var Functions_1 = require("./Functions");
exports.curry = Functions_1.curry;
exports.extractArgumentsFromFunction = Functions_1.extractArgumentsFromFunction;
var Objects_1 = require("./Objects");
exports.setDataAt = Objects_1.setDataAt;
exports.getDataAt = Objects_1.getDataAt;
exports.createPool = Objects_1.createPool;
var Common_1 = require("./Common");
exports.identity = Common_1.identity;
var Polyfill_1 = require("./Polyfill");
exports.requestAnimationFramePolyfill = Polyfill_1.requestAnimationFramePolyfill;
exports.objectAssignPolyfill = Polyfill_1.objectAssignPolyfill;
